version: "3.5"
services:
  ui:
    image: devopseasylearning/tarzan-ui:v0.0.1
    container_name: ui
    environment:
      - AUTH_HOST=auth
      - AUTH_PORT=8080
      - WEATHER_HOST=weather  
      - WEATHER_PORT=5000
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    depends_on:
      - redis
    networks:
      - tarnet
    expose:
      - "3000"
    ports:
      - "3755:3000"
    hostname: weather-ui

  auth:
    image: devopseasylearning/tarzan-auth:v0.0.1
    container_name: auth
    environment:
      - DB_HOST=db
      - DB_PASSWORD=my-secret-pw
    expose:
      - "8080"
    ports:
      - "8055:8080"
    networks:
      - tarnet
    depends_on:
      - db
    hostname: weather-auth

  weather:
    image: devopseasylearning/tarzan-weather:v0.0.1
    container_name: weather
    expose:
      - "5000"
    ports:
      - "5055:5000"
    environment:
      - APIKEY=ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    networks:
      - tarnet
    restart: always
    depends_on:
      - db
      - redis
    hostname: weather-weather

  db:
    image: devopseasylearning/tarzan-db:v0.0.1
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3355:3306"
    networks:
      - tarnet

  redis:
    image: redis
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6355:6379"
    networks:
      - tarnet
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    volumes:
      - redis-data:/data
networks:
  tarnet:
    driver: bridge
volumes:
  db-data:
  redis-data:
